---
- name: "Hammerspoon | MacOSX | Install Hammerspoon"
  community.general.homebrew_cask:
    name: hammerspoon
    state: present

- name: "Hammerspoon | MacOSX | Ensure ~/.hammerspoon exists"
  ansible.builtin.file:
    name: "{{ ansible_user_dir }}/.hammerspoon"
    state: directory
    mode: "0755"

- name: "Hammerspoon | MacOSX | Deploy Hammerspoon Configuration"
  ansible.builtin.copy:
    src: "{{ _files_path }}/config/"
    dest: "{{ ansible_user_dir }}/.hammerspoon"
    mode: "0644"
